services:
  - type: web
    name: tapcart-client
    env: node
    plan: free
    buildCommand: npm install && NODE_OPTIONS="--max-old-space-size=2048" npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
